name: Frontmatter Auto-Fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install tools
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install --save-dev gray-matter ajv ajv-formats glob js-yaml

      - name: Run frontmatter agent (write mode)
        run: node tools/add-frontmatter.js --write

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(frontmatter): add/normalize YAML frontmatter across specs & planning"
          branch: chore/frontmatter-autofix
          title: "Frontmatter auto-fix: add/normalize YAML metadata"
          body: |
            This PR was generated by the Frontmatter Agent.
            - Adds/normalizes YAML frontmatter for Markdown files in `specs/` and `planning/`.
            - Populates `id`, `title`, `type`, `status`, `domain`, `owner`, `last_reviewed`, and array fields.
            - Deterministic IDs based on path.
          labels: |
            chore
            automation
