name: Validate Spec Frontmatter

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      FRONTMATTER_PATHS: specs/**/*.md,planning/**/*.md,README.md,TODO.md
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install tools
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install --save-dev gray-matter ajv ajv-formats glob js-yaml

      - name: Validate specs
        run: node tools/validate-specs.js